#
# DDR related make flags
#
# DDR Debug flag
#
DEBUG_DDR		:=	0

# Proceed with make flags
$(eval $(call assert_boolean,DEBUG_DDR))
ifeq (${DEBUG_DDR},1)
  $(eval $(call add_define,DEBUG_DDR))
endif

# Default sed regexp - multiline due to syntax constraints
define sed-y
	"/^->/{s:->#\(.*\):/* \1 */:; \
	s:^->\([^ ]*\) [\$$#]*\([-0-9]*\) \(.*\):#define \1 \2 /* \3 */:; \
	s:^->\([^ ]*\) [\$$#]*\([^ ]*\) \(.*\):#define \1 \2 /* \3 */:; \
	s:->::; p;}"
endef

# Use filechk to avoid rebuilds when a header changes, but the resulting file
# does not
define filechk_offsets
	(set -e; \
	 echo "#ifndef $2"; \
	 echo "#define $2"; \
	 echo "/*"; \
	 echo " * DO NOT MODIFY."; \
	 echo " *"; \
	 echo " * This file was generated by Kbuild"; \
	 echo " */"; \
	 echo ""; \
	 sed -ne $(sed-y); \
	 echo ""; \
	 echo "#endif" )
endef

offsets-file	:= ${BUILD_PLAT}/generated/asm-offsets.h
offsets-asm 	:= ${BUILD_PLAT}/generated/asm-offsets.s
${offsets-file}: ${offsets-asm} FORCE
	$(Q)mkdir -p $(dir $@)
	$(call filechk,offsets,__TRIX_ASM_OFFSETS_H__)

${offsets-asm}: ${SD_PLAT_COM}/drivers/ddr/asm-offsets.c $(config-file) FORCE
	$(Q)mkdir -p $(dir $@)
	$(Q)$(CC) $(TF_CFLAGS) $(CFLAGS) -fverbose-asm -S -o $@ $<


include ${SD_PLAT_COM}/drivers/ddr/ddrsetting.mk

SD_DDR_SOURCES		:=	${SD_PLAT_COM}/drivers/ddr/ddr.c	\
				${SD_PLAT_COM}/drivers/ddr/umac.c	\
				${SD_PLAT_COM}/drivers/ddr/regtable.c	\
				${SD_PLAT_COM}/drivers/ddr/ddr_dqs.c	\
				${SD_PLAT_COM}/drivers/ddr/ddr_adjust.c

# Dependencies
${SD_PLAT_COM}/drivers/ddr/regtable.c : $(ddrsetting-header)

